### ISSUE TITLE
Multiple hide targets

### ISSUE THREAD

**Issue by johnSamilin** [oguzeroglu/Kompute#12]
Hi @oguzeroglu, thanks for maintaining this cool package.
When it comes to HideBehavior, it's not always convenient to have possibility to hide from just one target.
ex. I'd want an NPC in my imaginary game to hide from several enemies at the same time. Is this a use case worth implementing? An entity that's gonna hide may calculate suitable hiding spot for each of the "enemy" entities and use the closest one or just hide from the closest threatening entity.

**Comment by oguzeroglu** [comment]
Hey @johnSamilin, thanks!

The implementation of hide behaviour is pretty simple:

```javascript
// targetPosition is the position of the closest obstacle
return vectorPool.get().copy(hideableEntityPosition).sub(targetPosition).normalize().multiplyScalar(distanceAwayFromHideable).add(hideableEntityPosition);
```

So I'm not sure how this formula would work for multiple entities given its simplicity. Would we hide from the center point of each hide targets? We could alternatively draw an imaginary line from each hide target to the closest obstacle and find a point inside the imaginary area limited by these imaginary lines behind the obstacle however that seems geometrically more complex to implement.

I'd suggest you start simple first:

- Create a dummy entity
- Set this entity as the hide target
- For each frame calculate the center point of each of your actual hide targets
- dummyEntity.setPosition(centerPointYouCalculatedAbove)

so the hide behaviour would hide from the center point. Let's see if that works. If it does not, then I'd also consider implementing some sort of intelligence to my entity and just dynamically modify the hide target on the run based on some criteria (could be distance, whether it can be seen or not etc.).

**Comment by oguzeroglu** [comment]
> calculate suitable hiding spot for each of the "enemy" entities and use the closest

This could work for some game but not for some other game depending on many factors (weapons, speed, type of the threat etc.) so it's better not to implement this in the library IMO. Maybe you should try creating a separate `HideBehavior` for each hide target, then combine these behaviors with a `BlendedSteeringBehavior`.

> or just hide from the closest threatening entity.

Note that you could easily do that yourself in your game logic too by dynamically changing the hide target:
`steerable.setHideTargetEntity(closestHideTarget);`

**Comment by johnSamilin** [comment]
> Hey @johnSamilin, thanks!
> 
> The implementation of hide behaviour is pretty simple:
> 
> ```js
> // targetPosition is the position of the closest obstacle
> return vectorPool.get().copy(hideableEntityPosition).sub(targetPosition).normalize().multiplyScalar(distanceAwayFromHideable).add(hideableEntityPosition);
> ```
> 
> So I'm not sure how this formula would work for multiple entities given its simplicity. Would we hide from the center point of each hide targets? We could alternatively draw an imaginary line from each hide target to the closest obstacle and find a point inside the imaginary area limited by these imaginary lines behind the obstacle however that seems geometrically more complex to implement.
> 
> I'd suggest you start simple first:
> 
> * Create a dummy entity
> * Set this entity as the hide target
> * For each frame calculate the center point of each of your actual hide targets
> * dummyEntity.setPosition(centerPointYouCalculatedAbove)
> 
> so the hide behaviour would hide from the center point. Let's see if that works. If it does not, then I'd also consider implementing some sort of intelligence to my entity and just dynamically modify the hide target on the run based on some criteria (could be distance, whether it can be seen or not etc.).

What do you think about adding two methods to Steerable, `addHideTargetEntity` and `removeHideTargetEntity`? `setHideTargetEntity` should remain same and forcibly set hide target to the one passed in parameters?
